apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
  labels:
    app: hello-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-python
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
        - name: hello-python
          image: localhost:5000/hello-python:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-python
spec:
  selector:
    app: hello-python
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
